### PR TITLE
Move "ExerciseName.h" to #else block

### LINKED ISSUE #47: Move ExerciseName.h to the else block
- [ ] anagram
- [ ] bob
- [x] etl
- [ ] grade-school
- [ ] hamming
- [ ] hello-world
- [ ] leap
- [ ] nucleotide-count
- [ ] perfect-numbers
- [ ] phone-number
- [ ] robot-name
- [ ] space-age
- [ ] word-count

As a side effect of introducing this if else statement for the Example files, the else statement always complains when adding a new file. In order to make it less confusing to new users, we need to switch the ExerciseName.h to be the last statement. 
image

sample fix:
```
#if __has_include("RobotNameExample.h")
# import "RobotNameExample.h"
# else
# import "RobotName.h"
#endif
```

### LINKED ISSUE #75: anagram: Move "ExerciseName.h" to the #else block in xxTest.m file
See https://github.com/exercism/xobjective-c/issues/47

As a side effect of introducing this if else statement for the Example files, the else statement always complains when adding a new file. In order to make it less confusing to new users, we need to switch the ExerciseName.h to be the last statement. 
image

sample fix:
```
#if __has_include("RobotNameExample.h")
# import "RobotNameExample.h"
# else
# import "RobotName.h"
#endif
```

### PR DESCRIPTION
**Pull request by robtimp**
Resolves #47, #75, #76, #79, #80, #83, #84, #85, #86.

### CODE REVIEW

**Comment by robtimp** [comment]
@masters3d These were marked for first-timers, but they’ve been open for 3 months.

**Comment by masters3d** [comment]
:) I know, Thanks for cleaning up the issues.

**Comment by masters3d** [comment]
the issues didn't close automatically ;( maybe the commas ? You beat me to the last one

**Comment by kytrinyx** [comment]
I think it needs to be Resolves X, Resolves Y, Resolves Z - eh. So rarely does one pull request fix so many issues at once :)

**Pull request merged**
