### PR TITLE
Add introductory hello-world exercise

### PR DESCRIPTION
**Pull request by ramonh**
This addresses exercism/rossconf#2.

The hello-world exercise has three test cases, one for no name given, one for the name 'Alice' given and one for the name 'Bob' given. This is to avoid the hardcoding of a name into the solution.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks @ramonh -- do you have time to look into the build failure?

**Comment by ramonh** [comment]
Woops! Sorry about that, forgot to add it to config.json

**Comment by kytrinyx** [comment]
Oh, nice. That was easier than I feared (not knowing Objective-C and all). Would you mind squashing the commits?

**Comment by chillpop** [comment]
How about adding a `HELLO.md` similar to [this](https://github.com/exercism/exercism.io/issues/2021#issuecomment-93412385)?

**Comment by chillpop** [comment]
or is that no longer needed?

**Comment by ramonh** [comment]
I've squished the commits. 

About the `HELLO.md`, I believe it's already been taken care of [here](https://github.com/exercism/x-common/pull/77).

**Comment by chillpop** [comment]
Great.  Thanks Ramon!

**Comment by ramonh** [comment]
My pleasure! Thank you for your help and feedback!

**Pull request merged**
